kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: frontend
  namespace: blah
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: blah
        name: 'frontendbuilder:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/cloudacademy/openshift-voteapp-frontend-react'
      ref: master
  triggers:
    - type: GitHub
      github:
        secret: vUSzVvhMk402
  runPolicy: Serial
